const config = {
    controls: true,
    controlsTutorial: false,
    controlsLayout: 'bottom-right',
    controlsBackArrows: 'faded',
    progress: true,
    defaultTiming: 120,
    slideNumber: false,
    history: true,
    keyboard: true,
    overview: true,
    center: true,
    touch: false,
    loop: false,
    rtl: false,
    shuffle: false,
    fragments: true,
    embedded: false,
    help: true,
    showNotes: false,
    autoPlayMedia: null,
    autoSlide: 0,
    autoSlideStoppable: true,
    autoSlideMethod: Reveal.navigateNext,
    mouseWheel: false,
    hideAddressBar: true,
    previewLinks: false,
    transition: 'fade',
    transitionSpeed: 'default',
    backgroundTransition: 'fade',
    viewDistance: 3,
    parallaxBackgroundImage: '',
    parallaxBackgroundSize: '',
    parallaxBackgroundHorizontal: null,
	parallaxBackgroundVertical: null,
    display: 'block'
};

Reveal.initialize(config);
